
pandoc index.md \
       howto-use.md \
       phonetics/index.md \
       phonetics/general-information.md \
       phonetics/alphabet.md \
       phonetics/consonants.md \
       phonetics/letter-combinations.md \
       phonetics/sonants.md \
       phonetics/digraphs.md \
       phonetics/intonation.md \
       grammar/index.md \
       grammar/article.md \
       grammar/noun.md \
       grammar/adjective.md \
       grammar/pronouns.md \
       grammar/verb/index.md \
       grammar/verb/concept.md \
       grammar/verb/to-be.md \
       grammar/verb/to-have.md \
       grammar/verb/incentive.md \
       grammar/verb/imperative.md \
       grammar/verb/modal-verbs.md \
       grammar/tenses/index.md \
       grammar/tenses/indefinite.md \
       grammar/tenses/continuous.md \
       grammar/tenses/perfect.md \
       grammar/tenses/perfect-continuous.md \
       grammar/participles.md \
       grammar/gerund.md \
       grammar/numbers.md \
       grammar/sentence.md \
       grammar/there-is.md \
       grammar/questions.md \
       grammar/conjunctions.md \
       vocabulary/index.md \
       vocabulary/concept.md \
       vocabulary/geography.md \
       vocabulary/city.md \
       vocabulary/everyday-life.md \
       vocabulary/parts-of-speech.md \
       resources.md \
       -o collection.odt
